CREATE DATABASE zomato_mis;
USE zomato_mis;

ALTER TABLE restaurant 
RENAME COLUMN `ï»¿id` TO `id`;

ALTER TABLE restaurant
DROP COLUMN MyUnknownColumn,
DROP COLUMN `MyUnknownColumn_[0]`;

-- 1. Total revenue generated by city
SELECT r.city, ROUND(SUM(o.sales_amount), 2) AS Total_Revenue, COUNT(*) AS Total_orders
FROM orders AS o
JOIN restaurant AS r 
ON o.r_id = r.id
GROUP BY r.city
ORDER BY Total_Revenue DESC;

-- 2. Top 10 restaurants using revenue generated
SELECT r.name, r.city, ROUND(SUM(o.sales_amount), 2) AS Total_Revenue
FROM orders AS o
JOIN restaurant AS r 
ON o.r_id = r.id
GROUP BY r.name, r.city
ORDER BY Total_Revenue DESC
LIMIT 10;

-- 3. monthly revenue trend
SELECT DATE_FORMAT(STR_TO_DATE(order_date, '%d-%m-%Y'), '%Y-%m') AS Month, 
	ROUND(SUM(sales_amount), 2) AS Revenue
FROM orders
GROUP BY Month
ORDER BY Month;

-- 4. Revenue by customer occupation
SELECT u.Occupation,
       ROUND(SUM(o.sales_amount), 2) AS Total_Revenue,
       COUNT(*) AS Total_Orders
FROM orders o
JOIN users u 
ON o.user_id = u.user_id
GROUP BY u.Occupation
ORDER BY Total_Revenue DESC;

-- 5. Revenue by cuisine
SELECT r.cuisine,
       ROUND(SUM(o.sales_amount), 2) AS Total_Revenue,
       COUNT(*) AS Total_Orders
FROM orders o
JOIN restaurant r 
ON o.r_id = r.id
GROUP BY r.cuisine
ORDER BY Total_Revenue DESC
LIMIT 10;

-- 6. Average order value by gender
SELECT u.Gender,
       ROUND(AVG(o.sales_amount), 2) AS Avg_Order_Value,
       COUNT(*) AS Total_Orders
FROM orders o
JOIN users u ON o.user_id = u.user_id
GROUP BY u.Gender
ORDER BY Avg_Order_Value DESC;





